name: my first action

on:
    push:
        branches:
            - main
            - workflow_dispatch

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
            - name: say hello
              run: echo "hello from git hub action"

            - name: Check Node
              run: node --version

            - name: Check npm
              run: npm --version

            - name: check directory
              run: pwd

            - name: Show files
              run: ls -la